package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/looplj/axonhub/internal/objects"
	"github.com/looplj/axonhub/internal/server/biz"
)

// RequestResponseChunks is the resolver for the requestResponseChunks field.
func (r *queryResolver) RequestResponseChunks(ctx context.Context, requestID objects.GUID, first int, offset int) (*biz.ResponseChunkPage, error) {
	if first <= 0 || first > 200 {
		return nil, fmt.Errorf("first must be between 1 and 200")
	}
	if offset < 0 {
		return nil, fmt.Errorf("offset must be non-negative")
	}
	return r.requestService.LoadResponseChunksPaginated(ctx, requestID.ID, first, offset)
}
